apiVersion: v1
kind: Service
metadata:
  labels:
    app: node-exporter
    version: 0.18.1
  name: node-exporter
  namespace: monitor
spec:
  clusterIP: None
  ports:
    - name: scrape
      port: 9100
      targetPort: scrape
  selector:
    app: node-exporter
