apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: paymentservice
  labels:
    app: paymentservice
    type: hipster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
        type: hipster
    spec:
      containers:
        - name: paymentservice
          image: souljapanic/k8s-paymentservice:v0.0.1
